### ISSUE TITLE
All clusters disappear when one cluster disappears for a window.

### ISSUE THREAD

**Issue by ufon** [alex3165/react-mapbox-gl#188]
![image](https://cloud.githubusercontent.com/assets/4355972/24839910/a590eb26-1d6b-11e7-9f35-e5a1517a6eb4.png)
![image](https://cloud.githubusercontent.com/assets/4355972/24839919/b6815b1e-1d6b-11e7-8dd4-fc432f60116b.png)

How to fix it?

radius={60} minZoom={0} maxZoom={16} extent={1024} nodeSize={128} clusterThreshold={1}
my settings. thx.
And when i have clusterThreshold in 2..8 (demo settings) clusters dont worked.

**Comment by Pgsuarez** [comment]
`clusterThreshold` acts in a very strange way. It is the minimum number of clusters that can be displayed, so, if it's only possible to display 1 cluster and `clusterThreshold` is 2, the map will show all the marker (e.g. 20) instead of showing only 1 cluster. I think `clusterThreshold` shoud be the **maximum** number of clusters that can be displayed.

Try to set `clusterThreshold={0}`. I had to do that in order to clusters work as expected, i.e. show 1 or more clusters depending only on the radius prop.

**Comment by alex3165** [comment]
As I mentioned in https://github.com/alex3165/react-mapbox-gl/issues/206 the Cluster component would need a review on how it behave. I would be happy to have some help on this. Although I would suggest to use `Layout` and `Source` instead, have a look here: https://github.com/alex3165/react-mapbox-gl/issues/142

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/259 should fix all issues with cluster component

**Comment by alex3165** [comment]
Should be fixed with the latest version `2.0.3`
