### ISSUE TITLE
dependencies should be moved as peerDependencies

### ISSUE THREAD

**Issue by lamuertepeluda** [alex3165/react-mapbox-gl#190]
I think that

```json
  "dependencies": {
    "deep-equal": "^1.0.1",
    "mapbox-gl": "^0.35.0",
    "reduce-object": "^0.1.3",
    "supercluster": "^2.3.0"
  },
  "peerDependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
```

should become

```json
  "dependencies": {
  },
  "peerDependencies": {
    "deep-equal": "^1.0.1",
    "mapbox-gl": "^0.35.0",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "reduce-object": "^0.1.3",
    "supercluster": "^2.3.0"
  }
```

Then you should add the peers to devDependencies as well for testing, and in examples dependencies. This because they are external dependencies of your library just as react.

This way the user of your library is not constrained to embed mapboxgl and other modules twice in the bundle, e.g. if for some reason he's importing some stuff from mapboxgl using webpack, or wants to alias it for non-production builds.

**Comment by alex3165** [comment]
Thanks for the issue, you are right, see https://github.com/alex3165/react-mapbox-gl/commit/1db6ef9b5cace71ac8a4c7ed9e415d96f8cdb780

**Comment by philpl** [comment]
@alex3165 you don't want to move deep-equal and reduce-object into the peers. That's not necessary ;)

**Comment by connesc** [comment]
I agree with @philpl, this is not necessary.
By doing this, you require the user to bloat its own package.json with your internal dependencies, thus defeating the purpose of a package manager. And this can become very painful if you add or remove dependencies in future versions of `react-mapbox-gl`.
However, this sounds good for `mapbox-gl` since it is a core dependency.
