### ISSUE TITLE
GeoJSON layers does not seem to be visible anymore

### ISSUE THREAD

**Issue by lastsys** [alex3165/react-mapbox-gl#194]
I have had some code which worked fine until a couple of days ago.

My GeoJSON data is not visible anymore. Reproduction here:
https://github.com/lastsys/react-mapbox-gl-debug

Expected:
http://geojson.io/#id=gist:anonymous/c715b550ebd2cb5e7dfd40481c6aa97c&map=9/51.5583/-0.2115

**Comment by lastsys** [comment]
Got things working by using `GeoJSONLayer` instead. Failed using `Source` and `Layer` combination.

**Comment by alex3165** [comment]
Hey @lastsys Thanks for helping me to debug this issue, this has been fixed with this commit : https://github.com/alex3165/react-mapbox-gl/commit/b1cb8dcb2346daedc484f4889a307c6264075529#diff-7889a267378342b7f5ff9e7b08b38704R240 And it is released along with `renderWorldCopies` under the version 1.8.0.
