### ISSUE TITLE
Is is possible to dynamically add a Layer object?

### ISSUE THREAD

**Issue by chrabyrd** [alex3165/react-mapbox-gl#223]
Hello!

I have a Geosuggestion searchbox that returns a set of coordinates. I'd like to be able to press a button, and add a marker at those coordinates to an already instantiated map. However, I'm not seeing addLayer() defined in the docs. Is there a workaround?

Cheers!

**Comment by alex3165** [comment]
Hey, addLayer is abstracted by The Layer component, you will need to mount a Layer component with a Feature component for each marker. Have a look at the London cycle example.

**Comment by chrabyrd** [comment]
Hey, thanks for the quick reply!

I guess I'm not seeing it. When I read through the London cycle example I see the Layer and Feature components are static. They're instantiated with the map. What I'm trying to do is have a button that when clicked, adds a marker at a set of coordinates to an already instantiated map. 

The worst, hackiest way I can see doing this is to re-instantiate the map every time  a user adds a marker. However, that feels _wrong_.

Sorry if I'm not seeing it. But thank you for your help!

**Comment by z0d14c** [comment]
you can have a loop inside your component (that houses the Map component instance) that renders out layers inside of your Map component instance in a loop.

**Comment by chrabyrd** [comment]
Excellent! Thank you guys!

**Comment by HunteRoi** [comment]
Hey @chrabyrd !
I am currently building an open-source tool using the [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl) library and I have to dynamically add a Layer object along with its Feature object to the map. The context is that users add themself to an array and their default location are set on the fly, meaning that a movable\* marker as to be placed on the map.

I see that you closed this issue a while ago. Is there any chance you have some snippets for me to achieve my goal quickly? Deliverable is for next week :smile:

Thank you for your time!

\* movable : the user can drag and drop the marker on the map to update their coordinates

\_\_\_\_\_
As this issue is quite old and the library keeps getting updates, I am also mentioning @alex3165 for any appreciated input!
