### ISSUE TITLE
Is it possible to re-add source to trigger onSourceAdded?

### ISSUE THREAD

**Issue by thyforhtian** [alex3165/react-mapbox-gl#322]
Hi,
is it possible to re-add source to trigger `onSourceAdded`?

I thought I'd do that through removing and adding the source again through `map.removeSource/map.addSource` but it turned out calling `removeSource` adds it back straight away. Am I missing something? Is that a deliberate beahviour? Thank you.

**Comment by alex3165** [comment]
Hey @thyforhtian, you will need to unmount the `Source` component and mount it again. The source is added back because the `Source` component is mounted and you probably trigger a re-render which call `addSource` if the source is not on the map (for example when you previously removed it manually by calling `map.removeSource`).

**Comment by thyforhtian** [comment]
Thank you.
