### ISSUE TITLE
Feature coordinates of type `number[][]`

### ISSUE THREAD

**Issue by Pyppe** [alex3165/react-mapbox-gl#335]
Shouldn't the `Feature` component accept coordinates of type `number[][]`?

See https://github.com/alex3165/react-mapbox-gl/blob/master/src/feature.ts#L5:
```typescript
coordinates: number[] | number[][][] | number[][][][];
```

**Comment by alex3165** [comment]
Hey @Pyppe,

No actually the type signature `coordinates: number[] | number[][][] | number[][][][];` is right because a feature can be a symbol with coordinates `number[]`, a polygon (fill) `number[][][]` or a multipolygon (fill) `number[][][][]`.

But you are right it could also be `number[][]` for a route for example (line type).

Thanks for reporting, I pushed a fix: https://github.com/alex3165/react-mapbox-gl/commit/a95adb855492921ebaa7cfcb239eacf2c5674274

And released a patch `2.3.1`.
