### ISSUE TITLE
changing zoom not working

### ISSUE THREAD

**Issue by huaruiwu** [alex3165/react-mapbox-gl#34]
After scroll zooming, going back to the initial zoom set in the prop does not work because of the following. 

https://github.com/alex3165/react-mapbox-gl/blob/master/src/map.js#L196

Since the zoom prop does not change with scrolling it cannot go back to the original zoom level. Am I missing something here?

**Comment by alex3165** [comment]
Hi @huaruiwu it is an expected behaviour otherwise the zoom would go to the initial props as soon as you re-render the component. Why do you want to go back to your initial zoom ? If you have a "zoom to default" button an hacky solution would be to slightly change the value of the zoom, for example `12.001` instead of `12`.

**Comment by huaruiwu** [comment]
Hi @alex3165. I have for example, two locations. Each location has a center and zoom. Then I have a "Go To Location" button, which works on the center change but not zoom. Since they may have the same zoom number.

**Comment by alex3165** [comment]
Well i tested it more and you are right, it's working for the center because it is checking for the reference equality and as zoom is a number it only check for the value equality so set the variable again in the main component won't be detected, the only possible workaround i see is to wrap the zoom value into an array. I will fix it and a breaking change note to the readme.

**Comment by huaruiwu** [comment]
I noticed that too. Another thing is that it is also comparing array to object. Mapbox center is an object but the react Mapbox gl component uses array as center.

**Comment by alex3165** [comment]
I fixed the issue, you now have to pass an array to zoom
