### ISSUE TITLE
Marker performance issue

### ISSUE THREAD

**Issue by benrudolph** [alex3165/react-mapbox-gl#457]
Hi @alex3165, recently switched over to testing out your library for my project. So far it's greatly reduced complexity, however I've found that my performance has drastically decreased. I can easily generate 1000s of markers on my map and I've found that FPS starts to drop to 4 - 6 fps at just a few hundred. I've made a sample slow app:

https://github.com/benrudolph/react-mapbox-gl-debug

This only generates 1000 markers, and it's not quite as slow as my app, but you can still definitely start to see the delay. On a map that has a decent amount of complexity in the markers this gets unusable. I did some profiling and this was the result:

<img width="1866" alt="screen shot 2017-11-25 at 4 00 23 pm" src="https://user-images.githubusercontent.com/918514/33235277-84c3caaa-d1fa-11e7-85bc-5f8e918f6e1e.png">

Which points to a lot of time spend on firing events when moving the map and causing things to re-render. Let me know if you have any thoughts on this. Mapbox normally handles 1000s of markers without any delay

EDIT: Looked at the source code for this. I believe this is because this library doesn't use the native `Marker` element and applies its own HTML transforms to update marker's position.

**Comment by benrudolph** [comment]
Also for fwiw, I changed that setState call to be done on `moveend` instead of `move` and performance issues were immediately resolved. Obviously though the markers only update when the move ends which is also not ideal, but it does clearly point to the culprit.

**Comment by alex3165** [comment]
Hi @benrudolph, sorry for the late reply, do you have a specific requirement to use HTML Marker instead of the combination of `Layer` and `Feature`?

There is indeed lot of overhead using Marker as it need to listen `move` event to calculate the new projection when you change the viewport which is why it is slower.

**Comment by benrudolph** [comment]
Thanks @alex3165 that makes sense, I'll give that a shot. is there any scenario where one would use the Marker feature?

**Comment by alex3165** [comment]
It is useful only if you really have to display something complex on the map (video, image, react component...) but if you just want to display many icons you should rather use `Layer` and `Feature`

**Comment by kylebebak** [comment]
@alex3165 
Hey Alex, I've been using your library for a few weeks and I like it a lot. I have a question regarding `Marker` vs `Feature`, and I figured I'd ask it here instead of opening a new issue.

So, I can render ~800 `Feature`s on my map without any problem. However, as @benrudolph mentioned, rendering ~800 `Marker`s on the map slows my browser to a crawl.

One problem I have using a combination of `Layer` and `Feature` **is that not all the features are rendered to the map simultaneously** -- to see all 800 markers I have to zoom in very close and pan the map around. As you can see in the image below, if I'm zoomed out, only a small, seemingly random subset of the features I want to display are rendered.

<img width="650" alt="screen shot 2017-12-28 at 12 17 55 am" src="https://user-images.githubusercontent.com/1524088/34404803-a08793a6-eb64-11e7-9fcc-91edf7c46ad3.png">

I'd like to be able to render all 800 features on the map at once. If this isn't possible, this is a little surprising to me. Rendering this many markers to a map is a very common use case. I was able to do it years ago using Google Maps, as is demonstrated in the image below, without slowing the frame rate of the browser significantly.

<img width="849" alt="screen shot 2017-12-28 at 12 17 37 am" src="https://user-images.githubusercontent.com/1524088/34404857-ebc0ae7a-eb64-11e7-997d-569a33e92f3c.png">

Thank you for your help!

**Comment by codepreneur** [comment]
@benrudolph @alex3165 I am having same performance issues because I have to display complex things on the map and have to use html markers. Is there a way to setState on 'moveend' without tweaking the internals?

**Comment by codepreneur** [comment]
@benrudolph @alex3165 also when I try to use Layer/Feature my map/react app keeps refreshing infinitely.

**Comment by jordymeow** [comment]
@benrudolph @alex3165 Did you find a way to do that? I am also interested.

**Comment by benrudolph** [comment]
The way I do this that is more performant is to directly set geojson on a source component:
```
<Source id="myid" geoJsonSource={{ data: geojson, type: 'geojson' }} />
<Layer sourceId="myid" ...other props... />
```
One other big gotcha with this library is that the `Source` component will call `setData` when the geojson object reference changes (https://github.com/alex3165/react-mapbox-gl/blob/master/src/source.ts#L145). This happens _all_ the time if you rebuild your geojson object in your component. My suggestion here is to cache your geojson object on the component in a prop such as `this._cachedGeojson`. Then also keep a copy of the `MD5(JSON.stringify))`, then if the md5 of the geojson source changes, then update your `this._cachedGeojson`. This will save you from constantly calling `setData`.
