### ISSUE TITLE
Mobile browsers crashing after a few map loads

### ISSUE THREAD

**Issue by jnorris441** [alex3165/react-mapbox-gl#46]
I don't know if this has to do with garbage collection or running out of Web GL contexts...it seems if you load and kill 3 map instances, your page will crash mobile Safari. iOS 10.

**Comment by jnorris441** [comment]
I tried it on an Android phone with Chrome. I made it to 6 map loads before it crashed

**Comment by jnorris441** [comment]
I tried calling map.remove() in componentWillUnmount, that didn't work out

> mapbox-gl.bundle.js:1177 Uncaught TypeError: Cannot read property 'removeLayer' of null

**Comment by alex3165** [comment]
Have you tried to reproduce it using mapbox-gl-js directly without react-mapbox-gl ? Thanks for reporting it 👍

**Comment by philpl** [comment]
It might be related to the missing remove. I think you're right there. I'll open a PR

**Comment by philpl** [comment]
@jnorris441 @alex3165 My PR #47 adds the missing map removal that removes the WebWorkers and allows itself to be GC'ed. You couldn't just call `map.remove()`, since that would be executed before any underlying children are unmounted. Thus we need to defer the removal for that to work.

@jnorris441 Can you test whether the problem persists or not with that branch?

**Comment by jnorris441** [comment]
@alex3165 I haven't repro'd it directly yet

@philpl thanks for replying so quickly. That fix did not work for me, I still get the crash.

**Comment by jnorris441** [comment]
I opened an issue with mapbox gl https://github.com/mapbox/mapbox-gl-js/issues/3261

**Comment by philpl** [comment]
@jnorris441 Thanks a lot ;)
