### ISSUE TITLE
Is this going to be updated soon? 

### ISSUE THREAD

**Issue by suyesh** [alex3165/react-mapbox-gl#495]
```
warning " > react-mapbox-gl@3.4.1" has incorrect peer dependency "mapbox-gl@0.42.2".
warning " > react-mapbox-gl@3.4.1" has incorrect peer dependency "react@^15.6.1".
warning " > react-mapbox-gl@3.4.1" has incorrect peer dependency "react-dom@^15.6.1".
```

**Comment by redbmk** [comment]
@alex3165 Does `react-mapbox-gl` need to require a specific version of `mapbox-gl`? What if we just required `^0.42.2` (or `^0.43.0` for that matter)?

I feel like upgrading to react v16 though would be a breaking change so that would have to be part of version 4.

**Comment by Wykks** [comment]
It does need a specific version of `mapbox-gl`. Using `^` with `mapbox-gl` doesn't make sense, because they are not using semantic versioning (they are doing breaking changes in "minor version"). `0.43.0` doesn't work with `react-mapbox-gl` yet https://github.com/alex3165/react-mapbox-gl/issues/493

It already support react 16, the package.json need to be updated.

**Comment by Wykks** [comment]
package.json updated, closing in favor of #493

**Comment by redbmk** [comment]
Ah I didn't realize they weren't on semver. That's too bad.
