### ISSUE TITLE
Why zoom property is in array? Disabling Moving Method?

### ISSUE THREAD

**Issue by Altiano** [alex3165/react-mapbox-gl#57]
1. I think zoom property should be just primitive float, I don't see any reason to put it in array as it also different from Mapbox GL API

2. How to disable zoom method? I don't want to use any moving method.

**Comment by alex3165** [comment]
Yes I know it is an array on purpose, it was a Float before but in order to check for a reference equality on the map component it is required to pass it through an array : 
```
    const didZoomUpdate = (
      this.props.zoom !== nextProps.zoom &&
      nextProps.zoom !== map.getZoom()
    );
```

In this case if `this.props.zoom` is `[4]` and `nextProps.zoom` is a new array with a Float 4 inside it will break the equality because it does a reference check but it won't in case it is an Float.

If you have a good idea of how to solve it nicely I am happy to discuss of it.

**Comment by Altiano** [comment]
Maybe I'm not really understand what you're trying to say but as far as I know, if you're just want to comparing it, just use `==` (i.e. don't use strict equality `===`)

**Comment by alex3165** [comment]
Even with a `!=` it doesn't break the reference equality as if I pass an array because Int, String and Float are primitive types.

**Comment by philpl** [comment]
@Altiano We chose to change this back in version 0.8. It was a quick and easy fix to make sure that the zoom style was updated reliably, every time it's actually changed. Otherwise when the zoom level stays constant the styles are not updated.

The point is, we can't tell whether the zoom has changed, when the number itself has the same value. We can work around this in an easy way like this, by wrapping the number in an array, which is allocated  anew each time when you create one (note: `[] !== []`). This is not exactly fixing the problem, but we didn't see a reason to fix it properly and waste time on it.

To elaborate on equality in JS, `===` & `!==` stand for reference equality. It is technically not a strict equality, but to simplify it, it checks whether the values that are being pointed to are the same instance, so technically "in the same point in memory" (not being highly precise, since this doesn't always hold up).

I'm getting a bit off track here, but to further continue `==` & `!=` are type inferring before checking value equality. Details here: https://dorey.github.io/JavaScript-Equality-Table/

cc @alex3165

**Comment by DvStephen** [comment]
This is pulling up some history I appreciate, but I can't follow the reasoning here since you've essentially made a constant expression by strictly comparing an array this will always be true that they do not match, regardless of the values within them.

Is there an original context for this change?

**Comment by Wykks** [comment]
Everything is explained in the comment above by kitten; and still makes sense.
