### ISSUE TITLE
Popup can only have one child?

### ISSUE THREAD

**Issue by Altiano** [alex3165/react-mapbox-gl#60]
Is `Popup` can only one child intentional?

below code will result an error
````
<Popup>
   <A />
   <B />
</Popup>
````

to fix this I need to wrap the children in a div
````
<Popup>
   <div>
        <A />
        <B />
    </div>
</Popup>
````

**Comment by alex3165** [comment]
Yes indeed, Is it worth supporting multi children elements ?

**Comment by alex3165** [comment]
I will have a look it should be straightforward 👍

**Comment by alex3165** [comment]
@Altiano I have checked and there is no point on supporting multi children in the Popup. The signature of the render method is `ReactDOM.render(reactElement, domContainerNode)` it doesn't allow rendering of an array of ReactElement. I could wrap the children into a component and render this top level component but i think it is not an expected behaviour.

**Comment by Altiano** [comment]
how about `React.Children.toArray(children)` from the docs `https://facebook.github.io/react/docs/react-api.html#react.children.toarray` ?

**Comment by alex3165** [comment]
Hum I am not too sure this would solve the issue. If you have a good idea of how to do it, I am happy to review and eventually merge a PR for this. 👍
