### ISSUE TITLE
Upgrade to mapbox-gl 0.49

### ISSUE THREAD

**Issue by leBoer** [alex3165/react-mapbox-gl#637]
Will give us some more features, most notably [symbol-z-order](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-z-order), which is very useful for crowded maps.

**Comment by tstirrat15** [comment]
Mapbox being a [peer dependency](https://github.com/alex3165/react-mapbox-gl/blob/master/package.json#L67) means that you can install and use 0.49 if you so wish. Your package manager may complain, and there's a chance that functionality between this package and that one will break, but [the changelog](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0490) for mapbox-gl doesn't seem to have any huge breaking changes.

Question to the peer maintainers because I don't know the answer: is the idea of peer dependencies that there's a guarantee that a specific version of your package will work with a specific version of another package, but that they aren't packaged together?

**Comment by radeno** [comment]
@leBoer done with version 4.0

**Comment by mklopets** [comment]
Sorry for the delay, will look into updating.

Re: peer dependencies, one benefit is that you're guaranteed to have the same version of mapbox-gl in your app as is used by react-mapbox-gl. That way when you import something from one (either code or typescript types), everything should work together nicely.

**Comment by mklopets** [comment]
Didn't update any code, just the dependency for now. If using TS, the @types don't seem to be up-to-date. Released `v4.0.2` that uses `mapbox-gl@0.51.0`.

**Comment by mlg87** [comment]
[@types/mapbox-gl](https://www.npmjs.com/package/@types/mapbox-gl) just updated to `0.51.0` so that should take care of any tsc issues
