### ISSUE TITLE
What is the difference between Marker and Popup

### ISSUE THREAD

**Issue by vince1995** [alex3165/react-mapbox-gl#644]
I think the title says enough. I don't get it.

**Comment by mklopets** [comment]
A Marker can render any element, given a position. So you could use it for text, icons or even custom popups.

A Popup will render a popup as styled by Mapbox ([example](https://www.mapbox.com/mapbox-gl-js/example/popup/)).

So, you technically don't need a popup, but it makes rendering that sort of thing easier, because it handles a bunch of stuff for you ([docs](https://www.mapbox.com/mapbox-gl-js/api#popup)).

Closing the issue, but let me know if there's still confusion.
