### ISSUE TITLE
`withMap` HOC prevent us to override the default behaviors of components

### ISSUE THREAD

**Issue by thuanmb** [alex3165/react-mapbox-gl#661]
I have a use case that I want to override some behaviors in `GeoJSONLayer`, but with v.4.0.0, it return error because all components is now functional.

```
import { GeoJSONLayer }  from 'react-mapbox-gl';
 
class MyGeoJSONLayer extends GeoJSONLayer { // will throw runtime JS errors
    ...
}
```

I think it's better if we use `contextType` to access the `MapContext` instead of using `MapContext.Consumer`. For example:

```
import { MapContext }  from './context';
class GeoJSONLayer extends React.Component {
    static contextType = MapContext;
    ... 
    // use this.context as "map" instead of this.props.map
}
```

**Comment by AndyCJ** [comment]
In theory you should use composition rather than inheritance when working with React.

https://reactjs.org/docs/composition-vs-inheritance.html

 > React has a powerful composition model, and we recommend using composition instead of inheritance to reuse code between components.

https://reactjs.org/docs/composition-vs-inheritance.html#so-what-about-inheritance

> At Facebook, we use React in thousands of components, and we haven’t found any use cases where we would recommend creating component inheritance hierarchies.

If you do use composition rather than inheritance then it doesn't matter if the component is a class or a function, because they're both used in the same way.

It might be that `GeoJSONLayer` doesn't expose the customization that you need, but that's a problem with `GeoJSONLayer` rather than a reason to use inheritance.

Also, inheritance wouldn't let you change everything. Anything that's marked as private, such as [`private createLayer = (type: LayerType) => {`](https://github.com/alex3165/react-mapbox-gl/blob/master/src/geojson-layer.ts#L137) will be inaccessible via inheritance.

**Comment by daniel-hauser** [comment]
Closing the issue, the question was answered

Apart from that, `contextType` is supported in `react@16.6` and `react-mapbox-gl` is still dependent on `react@16.5`
