### ISSUE TITLE
Update all docs to have map prop (required) for <Source/>

### ISSUE THREAD

**Issue by mhuconcern** [alex3165/react-mapbox-gl#714]
Q: How do i use this without having access to Mapbox map object until style is loaded ? 

New definition
```
 export interface Props {
    id: string;
    geoJsonSource?: GeoJSONSourceRaw;
    tileJsonSource?: TilesJson;
    map: Map;
    onSourceAdded?: (source: GeoJSONSource | TilesJson) => void;
    onSourceLoaded?: (source: GeoJSONSource | TilesJson) => void;
} 
```

**Comment by mklopets** [comment]
I think the typing is broken due to the internal `withMap` context wrapper, as in typescript will actually currently accept anything as props on `<Source>`, but the `map` prop is a non-issue because if you look at the [implementation](https://github.com/alex3165/react-mapbox-gl/blob/25b924f942d323854ce3b332226d5e38dbd984be/src/source.ts#L147), the `map` property automatically comes via the context.
