### ISSUE TITLE
ZoomControl doesn't respect movingMethod

### ISSUE THREAD

**Issue by kimmobrunfeldt** [alex3165/react-mapbox-gl#76]
When adding a ZoomControl to map without any options, map's movingMethod option is not respected.

**Expected:**
![map2](https://cloud.githubusercontent.com/assets/1232405/20977780/3edc9e38-bcaf-11e6-931a-ee320dd976a0.gif)

Animated zooming. Definition in API docs: 

> movingMethod (Default: flyTo): String define the method used when changing the center or zoom position. 

**What happens:**
![map1](https://cloud.githubusercontent.com/assets/1232405/20977790/46aa0498-bcaf-11e6-8af5-19cecb8389b9.gif)

Zooming without animation.

**MyMap.js**:

```js
import React from 'react';
import ReactMapboxGl, { Layer, Feature, Marker, ZoomControl } from 'react-mapbox-gl';

const MyMap = React.createClass({
  getInitialState() {
    return {
      style: 'mapbox://styles/mapbox/light-v9',
    };
  },

  render() {
    const { state, props } = this;

    return (
      <div className="MyMap" style={{width: 500, height: 700}}>
          <ReactMapboxGl
            style={state.style}
            accessToken="pk.eyJ1IjoiZmFicmljOCIsImEiOiJjaWc5aTV1ZzUwMDJwdzJrb2w0dXRmc2d0In0.p6GGlfyV-WksaDV_KdN27A"
          >
            <ZoomControl />
          </ReactMapboxGl>
      </div>
    );
  }
});

export default MyMap;

```

**Comment by laznic** [comment]
I've also noticed the same thing as @kimmobrunfeldt, but hadn't time to open an issue about it. I do have an explanation and fix for this.

Why the zooming is "jumpy" is due to the onControlClick default settings:
```
onControlClick: (map, zoomDiff) => {
     map.setZoom(map.getZoom() + zoomDiff);
},
```

This causes the map to jump to a specific zoom level instead of animating to it. In the [Mapbox documentation](https://www.mapbox.com/mapbox-gl-js/api/#Map#zoomIn) there are another methods for setting the zoom level in order to have the zoom animation: `map.zoomIn()` and `map.zoomOut()`.

I'm currently using my custom onControlClick method in my app, but it would be better to have this animated functionality enabled by default. Below is the custom handler, which works just fine for me since I won't be needing to zoom in or out more than one level: 

```
onZoomClick(map, value) {
  value < 0 ? map.zoomOut() : map.zoomIn()
}
```

Also, since the `ZoomControl` has that `zoomDiff` prop, in order to fix it in this library, the function should probably be something like: 

```
onControlClick: (map, zoomDiff) => {
     zoomDiff > 0 ? 
          map.zoomIn({ level: map.getZoom() + zoomDiff }) : 
          map.zoomOut({ level: map.getZoom() - zoomDiff })
},
```

More than happy to do a PR for this if we get an OK from @alex3165.

**Comment by kimmobrunfeldt** [comment]
Ok awesome!

**Comment by alex3165** [comment]
Hey guys sure please feel free to submit a PR 👍
