### ISSUE TITLE
Marker position not updated after modification

### ISSUE THREAD

**Issue by calivet** [alex3165/react-mapbox-gl#84]
Hello,

I placed differents markers on map and when I change their coordinates with a drag bar, their position is not updated after recalling render function. But if I interact with map (drap, zoom), their position is updated (I precise that render is not called during interaction).

I have no problem with symbol layer, but I need an image point.

Thanks

**Comment by alex3165** [comment]
If you display lot of markers, I would still suggest you to define a symbol (on mapbox studio) for each images you have and use the `Symbol` instead of the `Marker` which is more efficient.

Though, indeed the `Marker` is not updated and this is a real issue, I forgot this with the new version of the Marker implemented in React

**Comment by calivet** [comment]
Yes I think I'll do that.

Thank you very much for your fast response.

**Comment by alex3165** [comment]
Should be fixed with https://github.com/alex3165/react-mapbox-gl/pull/87

**Comment by alex3165** [comment]
Should be good with the version `0.22.0` 👍

**Comment by calivet** [comment]
I confirm, now it works ! Good job! Thank you very much

**Comment by Altiano** [comment]
How many is "lot of markers" ?
